class TasheUi {
  constructor() { this.modal = document.getElementById('modal'); this.contextMenu = document.getElementById('contextMenu'); }
  toast(message) { const el = document.createElement('div'); el.className = 'toast'; el.textContent = message; document.body.appendChild(el); setTimeout(() => el.remove(), 3200); }
  prompt({ title, label, type = 'text', value = '' }) { return new Promise(resolve => { this.modal.hidden = false; document.getElementById('modalTitle').textContent = title; document.getElementById('modalBody').innerHTML = `<label>${label}<input class="modalInput" id="modalInput" type="${type}" value="${value.replaceAll('"','&quot;')}"></label>`; document.getElementById('modalActions').innerHTML = '<button class="ghost" data-cancel>Cancel</button><button class="primary" data-ok>OK</button>'; const input = document.getElementById('modalInput'); input.focus(); const close = val => { this.modal.hidden = true; resolve(val); }; this.modal.querySelector('[data-cancel]').onclick = () => close(null); this.modal.querySelector('[data-ok]').onclick = () => close(input.value); input.onkeydown = e => { if (e.key === 'Enter') close(input.value); if (e.key === 'Escape') close(null); }; }); }
  preview({ title, html }) { this.modal.hidden = false; document.getElementById('modalTitle').textContent = title; document.getElementById('modalBody').innerHTML = html; document.getElementById('modalActions').innerHTML = '<button class="primary" data-ok>Close</button>'; this.modal.querySelector('[data-ok]').onclick = () => { this.modal.hidden = true; }; }
  menu(x, y, actions) { this.contextMenu.innerHTML = actions.map((a,i) => `<button data-i="${i}">${a.icon || ''}<span>${a.label}</span></button>`).join(''); this.contextMenu.style.left = `${x}px`; this.contextMenu.style.top = `${y}px`; this.contextMenu.hidden = false; this.contextMenu.querySelectorAll('button').forEach(btn => btn.onclick = () => { this.contextMenu.hidden = true; actions[btn.dataset.i].run(); }); }
  hideMenu() { this.contextMenu.hidden = true; }
}
window.TasheUi = TasheUi;
