const Utils = {
  formatBytes(bytes) { if (!bytes) return '—'; const units = ['B','KB','MB','GB']; let value = bytes, i = 0; while (value >= 1024 && i < units.length - 1) { value /= 1024; i++; } return `${value.toFixed(value >= 10 || i === 0 ? 0 : 1)} ${units[i]}`; },
  icon(item) { if (item.type === 'folder') return item.protected ? '🔐' : '📁'; const m = item.mimeType || ''; if (m.startsWith('image/')) return '🖼️'; if (m.startsWith('video/')) return '🎬'; if (m.startsWith('audio/')) return '🎵'; if (m.includes('pdf')) return '📕'; if (m.includes('zip') || m.includes('compressed')) return '🗜️'; if (m.startsWith('text/')) return '📄'; return '📎'; },
  canPreview(item) { const m = item.mimeType || ''; return item.type === 'file' && (m.startsWith('image/') || m.startsWith('video/') || m.startsWith('audio/') || m.includes('pdf') || m.startsWith('text/')); },
  sort(items, mode) { return [...items].sort((a,b) => mode === 'newest' ? new Date(b.modifiedTime) - new Date(a.modifiedTime) : mode === 'oldest' ? new Date(a.modifiedTime) - new Date(b.modifiedTime) : mode === 'size' ? (b.size || 0) - (a.size || 0) : mode === 'type' ? `${a.type}${a.mimeType}`.localeCompare(`${b.type}${b.mimeType}`) : a.name.localeCompare(b.name)); },
  safeName(name) { return String(name || '').replace(/[\\/:*?"<>|\u0000-\u001F]/g, ' ').replace(/\s+/g, ' ').trim(); },
  debounce(fn, delay = 160) { let t; return (...args) => { clearTimeout(t); t = setTimeout(() => fn(...args), delay); }; },
  readFile(file, onProgress) { return new Promise((resolve, reject) => { const reader = new FileReader(); const start = performance.now(); reader.onprogress = e => { if (e.lengthComputable) onProgress?.({ loaded: e.loaded, total: e.total, elapsed: performance.now() - start }); }; reader.onerror = () => reject(reader.error); reader.onload = () => resolve({ name: file.name, mimeType: file.type || 'application/octet-stream', size: file.size, data: reader.result }); reader.readAsDataURL(file); }); }
};
